require('plugins')
require('remap')

require('plugins.lualine')
require('plugins.tree')
require('plugins.treesitter')
require('plugins.barbar')
require('plugins.mason')
require('plugins.cmp')
require('plugins.lsp')
require('plugins.telescope')
require('plugins.colors')
require('plugins.dap')
require('plugins.harpoon')
require('plugins.undotree')
